/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/altarmy/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Altarmy Files */
        get: operations["get_altarmy_files_api_altarmy_files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auctionator/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Auctionator Files */
        get: operations["get_auctionator_files_api_auctionator_files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Characters */
        get: operations["get_characters_api_characters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/game-data/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update Game Data */
        post: operations["update_game_data_api_game_data_update_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Rank
         * @description What the selected realm/faction's characters can craft, most profitable first. Bounds are
         *     inclusive; an omitted bound is unbounded (so losses are included unless `min_profit` is set).
         */
        get: operations["get_rank_api_rank_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reload
         * @description Drop the cached market, e.g. after changing the database from the command line.
         */
        post: operations["reload_api_reload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/selection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Selection
         * @description Switch realm/faction; that realm's Auctionator prices replace the previous ones.
         */
        put: operations["put_selection_api_selection_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Sources */
        put: operations["put_sources_api_sources_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Status
         * @description Also the addon file watcher: re-imports Alt Army and Auctionator data the game has rewritten.
         */
        get: operations["get_status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Now
         * @description Re-import both addon files even if they look unchanged.
         */
        post: operations["sync_now_api_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CharacterOut */
        CharacterOut: {
            /** Class File */
            class_file: string;
            /** Level */
            level: number;
            /** Name */
            name: string;
            /** Professions */
            professions: components["schemas"]["ProfessionOut"][];
        };
        /** Characters */
        Characters: {
            /** Groups */
            groups: components["schemas"]["GroupOut"][];
            selection: components["schemas"]["SelectionModel"] | null;
        };
        /** ExitOut */
        ExitOut: {
            /** Kind */
            kind: string;
            /** Mail To */
            mail_to: string;
            /** Materials */
            materials: components["schemas"]["MaterialOut"][];
            /** Postage */
            postage: number;
            /** Value */
            value: number;
        };
        /** GroupOut */
        GroupOut: {
            /** Characters */
            characters: components["schemas"]["CharacterOut"][];
            /** Faction */
            faction: string;
            /** Realm */
            realm: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ItemCount */
        ItemCount: {
            /** Count */
            count: number;
            /** Item Id */
            item_id: number;
        };
        /**
         * ItemInfo
         * @description Everything an item tooltip shows.
         */
        ItemInfo: {
            /** Ah Price */
            ah_price: number | null;
            /** Bonding */
            bonding: number;
            /** Class Id */
            class_id: number;
            /** Container Slots */
            container_slots: number;
            /** Description */
            description: string | null;
            /** Icon */
            icon: string | null;
            /** Id */
            id: number;
            /** Inventory Type */
            inventory_type: number;
            /** Item Delay */
            item_delay: number;
            /** Name */
            name: string;
            /** Quality */
            quality: number;
            /** Required Level */
            required_level: number;
            /** Required Skill */
            required_skill: string | null;
            /** Required Skill Rank */
            required_skill_rank: number;
            /** Sell Price */
            sell_price: number;
            /** Subclass Name */
            subclass_name: string | null;
            /** Vendor Price */
            vendor_price: number | null;
        };
        /**
         * MaterialOut
         * @description One possible disenchant result.
         */
        MaterialOut: {
            /** Chance */
            chance: number;
            /** Item Id */
            item_id: number;
            /** Max Count */
            max_count: number;
            /** Min Count */
            min_count: number;
            /** Name */
            name: string;
            /** Value */
            value: number | null;
        };
        /**
         * NodeOut
         * @description One item in a craft's reagent tree: bought (no inputs) or crafted from its inputs, possibly by
         *     another character who then mails it on.
         */
        NodeOut: {
            /** Cost */
            cost: number;
            /** Crafter */
            crafter: string;
            /** Crafts */
            crafts: number;
            /** Inputs */
            inputs: components["schemas"]["NodeOut"][];
            /** Item Id */
            item_id: number;
            /** Made */
            made: number;
            /** Mail To */
            mail_to: string;
            /** Name */
            name: string;
            /** Postage */
            postage: number;
            /** Quantity */
            quantity: number;
            /** Source */
            source: string;
            /** Via */
            via: string;
        };
        /** ProfessionOut */
        ProfessionOut: {
            /** Max Rank */
            max_rank: number;
            /** Name */
            name: string;
            /** Rank */
            rank: number;
            /** Recipes */
            recipes: number;
        };
        /** RankResponse */
        RankResponse: {
            /** Classes */
            classes: {
                [key: string]: string;
            };
            /** Items */
            items: {
                [key: string]: components["schemas"]["ItemInfo"];
            };
            /** Results */
            results: components["schemas"]["RankResult"][];
            /** Total */
            total: number;
        };
        /** RankResult */
        RankResult: {
            /** Best Exit */
            best_exit: string;
            /** Cost */
            cost: number;
            /** Crafter */
            crafter: string;
            /** Crafters */
            crafters: string[];
            /** Exits */
            exits: components["schemas"]["ExitOut"][];
            /** Mail To */
            mail_to: string;
            /** Output Count */
            output_count: number;
            /** Output Item Id */
            output_item_id: number;
            /** Output Name */
            output_name: string;
            /** Postage */
            postage: number;
            /** Profession */
            profession: string;
            /** Profit */
            profit: number;
            /** Reagents */
            reagents: components["schemas"]["ItemCount"][];
            /** Recipe */
            recipe: string;
            /** Recipe Id */
            recipe_id: number;
            /** Revenue */
            revenue: number;
            /** Roi */
            roi: number;
            /** Steps */
            steps: components["schemas"]["StepOut"][];
            tree: components["schemas"]["NodeOut"];
        };
        /**
         * SelectionModel
         * @description A realm and faction: whose recipes count and which auction house prices them.
         */
        SelectionModel: {
            /** Faction */
            faction: string;
            /** Realm */
            realm: string;
        };
        /** SourceFiles */
        SourceFiles: {
            /** Default */
            default: string | null;
            /** Files */
            files: string[];
        };
        /**
         * Sources
         * @description SavedVariables files to sync from; a missing field keeps that source.
         */
        Sources: {
            /** Altarmy Path */
            altarmy_path?: string | null;
            /** Auctionator Path */
            auctionator_path?: string | null;
        };
        /** Status */
        Status: {
            /** Altarmy Path */
            altarmy_path: string | null;
            /** Auctionator Path */
            auctionator_path: string | null;
            /** Auctionator Realm */
            auctionator_realm: string | null;
            /** Build */
            build: string | null;
            /** Characters */
            characters: number;
            /** Data Version */
            data_version: number;
            /** Db Path */
            db_path: string;
            /** Items */
            items: number;
            /** Last Altarmy Sync */
            last_altarmy_sync: string | null;
            /** Last Auctionator Import */
            last_auctionator_import: string | null;
            /** Last Auctionator Sync */
            last_auctionator_sync: string | null;
            /** Prices */
            prices: number;
            /** Recipes */
            recipes: number;
            selection: components["schemas"]["SelectionModel"] | null;
            /** Warnings */
            warnings: string[];
        };
        /** StepOut */
        StepOut: {
            /**
             * Action
             * @enum {string}
             */
            action: "buy" | "craft" | "mail" | "sell";
            /** Item Id */
            item_id: number;
            /** Name */
            name: string;
            /** Quantity */
            quantity: number;
            /** Value */
            value: number;
            /** Via */
            via: string;
            /** Who */
            who: string;
        };
        /** UpdateResult */
        UpdateResult: {
            /** Build */
            build: string;
            /** Disenchant Rows */
            disenchant_rows: number;
            /** Items */
            items: number;
            /** Recipes */
            recipes: number;
            /** Updated */
            updated: boolean;
            /** Vendor Items */
            vendor_items: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_altarmy_files_api_altarmy_files_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceFiles"];
                };
            };
        };
    };
    get_auctionator_files_api_auctionator_files_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceFiles"];
                };
            };
        };
    };
    get_characters_api_characters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Characters"];
                };
            };
        };
    };
    update_game_data_api_game_data_update_post: {
        parameters: {
            query?: {
                /** @description skip the rebuild if the newest build is loaded */
                only_if_new?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rank_api_rank_get: {
        parameters: {
            query?: {
                /** @description rank every recipe of the characters' professions, not just learned ones */
                include_unlearned?: boolean;
                /** @description ways the crafts may be sold */
                exits?: ("vendor" | "ah" | "disenchant")[];
                /** @description copper */
                min_cost?: number | null;
                /** @description copper */
                max_cost?: number | null;
                /** @description copper */
                min_profit?: number | null;
                /** @description copper */
                max_profit?: number | null;
                /** @description profit / cost (0.5 = 50%) */
                min_roi?: number | null;
                /** @description profit / cost (0.5 = 50%) */
                max_roi?: number | null;
                top?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reload_api_reload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    put_selection_api_selection_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectionModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_sources_api_sources_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Sources"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    sync_now_api_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
}
